### ISSUE TITLE
更多菜单某一类筛选可以设置为单选吗

### ISSUE THREAD

**Issue by 121753961** [zeqinjie/ZQFilterMenuView#1]
更多菜单某一类筛选可以设置为单选吗
![image](https://user-images.githubusercontent.com/12001672/90993872-3191c980-e5e9-11ea-92c5-f86f2fb65ebf.png)
像图片上是可以多选，我想他只能单选，比如：特色只能选一个，面积也只能选一个
@zeqinjie

**Comment by zeqinjie** [comment]
> 更多菜单某一类筛选可以设置为单选吗
> 
> ![image](https://user-images.githubusercontent.com/12001672/90993872-3191c980-e5e9-11ea-92c5-f86f2fb65ebf.png)
> 
> 像图片上是可以多选，我想他只能单选，比如：特色只能选一个，面积也只能选一个
> 
> @zeqinjie 

可以的，单选复选通过模型的属性控制。

**Comment by zeqinjie** [comment]
@121753961 可以的，单选复选通过模型的 selectMode 属性值控制，你看demo 有示例的
