### ISSUE TITLE
关于点击更多下面的按钮时候其他按钮的颜色会变亮一下

### ISSUE THREAD

**Issue by yxx19950523** [zeqinjie/ZQFilterMenuView#2]
如题，问题咋解决，我以前自己写筛选的时候，用collec也是，点击的时候其他的cell就会高亮一下

**Comment by zeqinjie** [comment]
//    [self.moreCollectionView reloadSections:[NSIndexSet indexSetWithIndex:indexPath.section]];
    [self.moreCollectionView reloadData];
修改成全部 reloadData 就好了

**Comment by zeqinjie** [comment]
> 如题，问题咋解决，我以前自己写筛选的时候，用collec也是，点击的时候其他的cell就会高亮一下

// [self.moreCollectionView reloadSections:[NSIndexSet indexSetWithIndex:indexPath.section]];
[self.moreCollectionView reloadData];
修改成全部 reloadData 就好了
