### ISSUE TITLE
有方法可以实现：设置指定ZQTabControl的选中位置？

### ISSUE THREAD

**Issue by tongyuling** [zeqinjie/ZQFilterMenuView#4]
有方法可以实现：设置指定ZQTabControl的选中位置？
点击其他按钮，ZQTabControl选中排序-高价优先，选中状态怎么设置？
<img width="214" alt="image" src="https://user-images.githubusercontent.com/11831758/122520166-da605800-d045-11eb-9713-fa03fe7db183.png">

**Comment by zeqinjie** [comment]
1. 设置 ZQItemModel 对象 seleceted 为 true
2. ZQTabControl 设置 - (void)adjustTitle:(NSString *)title textColor:(UIColor *)color

**Comment by zeqinjie** [comment]
> 有方法可以实现：设置指定ZQTabControl的选中位置？
> 点击其他按钮，ZQTabControl选中排序-高价优先，选中状态怎么设置？
> <img alt="image" width="214" src="https://user-images.githubusercontent.com/11831758/122520166-da605800-d045-11eb-9713-fa03fe7db183.png">

- 设置 ZQItemModel 对象 seleceted 为 true
- ZQTabControl 设置 - (void)adjustTitle:(NSString *)title textColor:(UIColor *)color
